FROM python:3.11-slim

WORKDIR /srv

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY app ./app
COPY worker ./worker

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
